service: sentiment-analysis

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  profile: <YOUR_AWS_PROFILE>
  region: us-east-1
  stage: dev
  timeout: 60cat
  iamRoleStatements:
  - Effect: Allow
    Action:
    - logs:*
    - comprehend:*
    Resource:
    - arn:aws:logs:*:*:*
    - "*"

package:
  artifact: build/distributions/aws-java-simple-http-endpoint.zip

functions:
  sentimentAnalyzer:
    handler: com.serverless.Handler
    events:
      - http:
          path: /
          method: get
